# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XX2v6OEFBHF3UEFgSqFUCOnlfQNSQYUr
"""

!pip install markovify

import markovify

text = """
Artificial Intelligence is changing the world. Artificial Intelligence helps people solve problems.
Technology improves education and healthcare. Machine learning is a branch of Artificial Intelligence.
Students use technology for learning and research. Generative AI creates text, images, and other content.
Data science helps organizations make better decisions. Artificial Intelligence is used in healthcare.
Artificial Intelligence is used in education. Technology helps students learn new skills.
Machine learning improves prediction accuracy. Deep learning is a subset of machine learning.
"""

text_model = markovify.Text(text, state_size=1)

print("Generated Sentences:\n")

for i in range(10):
    print(text_model.make_sentence(tries=100))